from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class OperationType(str, Enum):
    """Supported arithmetic operation types."""

    ADD = "add"
    SUBTRACT = "subtract"
    MULTIPLY = "multiply"
    DIVIDE = "divide"


class CalculationRequest(BaseModel):
    """Request schema for arithmetic calculations."""

    model_config = ConfigDict(extra="forbid")

    operand_a: Decimal = Field(
        ...,
        description="The primary operand for the arithmetic operation.",
    )
    operand_b: Decimal = Field(
        ...,
        description="The secondary operand for the arithmetic operation.",
    )
    operation: OperationType = Field(
        ...,
        description="The binary arithmetic operator to apply.",
    )


class CalculationResponse(BaseModel):
    """Response schema containing calculation metadata and evaluated result."""

    model_config = ConfigDict(extra="forbid")

    operand_a: Decimal = Field(..., description="The original primary operand.")
    operand_b: Decimal = Field(..., description="The original secondary operand.")
    operation: OperationType = Field(..., description="The evaluated operation.")
    result: Decimal = Field(..., description="The high-precision calculation result.")
    calculated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when calculation completed.",
    )


class ProblemDetail(BaseModel):
    """RFC 7807 problem details specification response schema."""

    model_config = ConfigDict(extra="forbid")

    type: str = Field(..., description="URI reference identifying the problem type.")
    title: str = Field(..., description="Human-readable summary of the problem.")
    status: int = Field(..., description="HTTP status code generated by origin server.")
    detail: str = Field(..., description="Human-readable explanation specific to occurrence.")
    instance: str | None = Field(default=None, description="URI reference identifying occurrence.")
